# Generated by Django 5.1.7 on 2025-11-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PieceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=200)),
                ('shipper_name', models.CharField(max_length=200)),
                ('shipper_phone', models.CharField(max_length=200)),
                ('shipper_address', models.CharField(max_length=255)),
                ('shipper_email', models.EmailField(max_length=254)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=200)),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('packages', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_freight', models.CharField(max_length=200)),
                ('carrier_reference_no', models.CharField(blank=True, max_length=200, null=True)),
                ('departure_time', models.TimeField()),
                ('pickup_time', models.TimeField()),
                ('pickup_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.carrier')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.courier')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_country', to='shipments.country')),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.mode')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country', to='shipments.country')),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.paymentmode')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.product')),
                ('shipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.shipmenttype')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.statustype')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('piece_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.piecetype')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages_list', to='shipments.shipment')),
            ],
        ),
    ]
