# Generated by Django 5.1.7 on 2025-11-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_populate_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_country', to='shipments.country'),
        ),
    ]
